In [1]:
#Q2 Row Echelon Form:

import numpy as np
import sympy as sp

In [2]:

np.random.seed(17)
A=np.random.randint(0,10,(5,5))
A

array([[1, 6, 6, 9, 0],
       [6, 4, 7, 4, 7],
       [1, 1, 9, 8, 2],
       [3, 6, 6, 9, 9],
       [1, 5, 1, 0, 5]])

In [10]:
A=sp.Matrix(A)
A

Matrix([
[1, 6, 6,  9, 0],
[0, 1, 0,  1, 0],
[0, 0, 1,  1, 0],
[0, 0, 0,  1, 1],
[0, 0, 0, -3, 5]])

In [3]:
A[1]=A[1]-6*A[0]
A[2]=A[2]-A[0]
A[3]=A[3]-3*A[0]
A[4]=A[4]-A[0]
A

array([[  1,   6,   6,   9,   0],
       [  0, -32, -29, -50,   7],
       [  0,  -5,   3,  -1,   2],
       [  0, -12, -12, -18,   9],
       [  0,  -1,  -5,  -9,   5]])

In [4]:
A[1]=A[1]/-32
A

array([[  1,   6,   6,   9,   0],
       [  0,   1,   0,   1,   0],
       [  0,  -5,   3,  -1,   2],
       [  0, -12, -12, -18,   9],
       [  0,  -1,  -5,  -9,   5]])

In [5]:
A[2]=A[2]+A[1]*5
A[3]=A[3]+12*A[1]
A[4]=A[4]+A[1]
A

array([[  1,   6,   6,   9,   0],
       [  0,   1,   0,   1,   0],
       [  0,   0,   3,   4,   2],
       [  0,   0, -12,  -6,   9],
       [  0,   0,  -5,  -8,   5]])

In [6]:
A[2]=A[2]/3
A

array([[  1,   6,   6,   9,   0],
       [  0,   1,   0,   1,   0],
       [  0,   0,   1,   1,   0],
       [  0,   0, -12,  -6,   9],
       [  0,   0,  -5,  -8,   5]])

In [7]:
A[3]=A[3]+12*A[2]
A[4]=A[4]+5*A[2]
A

array([[ 1,  6,  6,  9,  0],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  1,  1,  0],
       [ 0,  0,  0,  6,  9],
       [ 0,  0,  0, -3,  5]])

In [8]:
A[3]=A[3]/6
A

array([[ 1,  6,  6,  9,  0],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  1,  1,  0],
       [ 0,  0,  0,  1,  1],
       [ 0,  0,  0, -3,  5]])