In [76]:
#Q3 Singular Value Decomposition 
import numpy as np
import sympy as sp

In [77]:
np.random.seed(17)
A=np.random.randint(0,10,(5,5))
A

array([[1, 6, 6, 9, 0],
       [6, 4, 7, 4, 7],
       [1, 1, 9, 8, 2],
       [3, 6, 6, 9, 9],
       [1, 5, 1, 0, 5]])

In [78]:
U,s,VT= np.linalg.svd(A)
U

array([[-0.43538398,  0.49632843, -0.58070328, -0.44660856, -0.16560004],
       [-0.4721125 , -0.38812273,  0.51419293, -0.5454511 , -0.25408515],
       [-0.43510099,  0.51476426,  0.46255004,  0.19367148,  0.54244235],
       [-0.60244294, -0.26490568, -0.19859246,  0.66192893, -0.29882872],
       [-0.18788347, -0.51755345, -0.38078581, -0.16542472,  0.7242065 ]])

In [79]:
S=np.zeros((A.shape[0], A.shape[1]))
S[:A.shape[1],:A.shape[0]]=np.diag(s)
S

array([[25.21604797,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  9.2542578 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  5.48110925,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  3.27423941,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.93557094]])

In [80]:
VT

array([[-0.22598197, -0.37634485, -0.54074855, -0.58334678, -0.41784475],
       [-0.28418424, -0.24172197,  0.30115892,  0.50230153, -0.71958758],
       [ 0.36314568, -0.74079562,  0.49364836, -0.22924002,  0.15201109],
       [-0.52081762, -0.46524829, -0.28972128,  0.39870352,  0.51902804],
       [-0.68194258,  0.18628182,  0.53783564, -0.44258809,  0.12289018]])

In [81]:
M=U@S@VT
np.round(M)

array([[1., 6., 6., 9., 0.],
       [6., 4., 7., 4., 7.],
       [1., 1., 9., 8., 2.],
       [3., 6., 6., 9., 9.],
       [1., 5., 1., 0., 5.]])

In [82]:
A==np.round(M)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [83]:
# Rank 2 Approximation

A2 = np.dot(U[:, :2], np.dot(np.diag(s[:2]), VT[:2, :]))
np.round(A2)

array([[1., 3., 7., 9., 1.],
       [4., 5., 5., 5., 8.],
       [1., 3., 7., 9., 1.],
       [4., 6., 7., 8., 8.],
       [2., 3., 1., 0., 5.]])

In [84]:
# Rank 3 Approximation
A3 = np.dot(U[:, :3], np.dot(np.diag(s[:3]), VT[:3, :]))
np.round(A3)

array([[0., 5., 6., 9., 1.],
       [5., 3., 7., 4., 8.],
       [2., 1., 9., 8., 2.],
       [4., 7., 7., 8., 8.],
       [2., 4., 0., 1., 5.]])